import React, { useEffect, useState } from 'react';
import { api } from '../services/api';
import { FileText, Download, Copy, RefreshCw, Check } from 'lucide-react';

export const ReportsPage: React.FC = () => {
  const [reportData, setReportData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    loadReport();
  }, []);

  const loadReport = async () => {
    try {
      setLoading(true);
      const data = await api.getExecutiveReport();
      setReportData(data);
    } catch (err) {
      console.error("Failed to load report", err);
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (reportData?.report_md) {
      navigator.clipboard.writeText(reportData.report_md);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    if (reportData?.report_md) {
      const element = document.createElement("a");
      const file = new Blob([reportData.report_md], { type: 'text/markdown' });
      element.href = URL.createObjectURL(file);
      element.download = `SupplyMind_Executive_Risk_Report_${new Date().toISOString().substring(0,10)}.md`;
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    }
  };

  return (
    <div className="space-y-6 pb-12">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold text-white tracking-tight flex items-center gap-2">
            <FileText className="w-5 h-5 text-indigo-400" />
            <span>Executive & Technical Risk Reports</span>
          </h1>
          <p className="text-xs text-slate-400 font-mono mt-0.5">
            Auto-synthesized executive briefings generated by Multi-Agent Report Agent
          </p>
        </div>

        <div className="flex items-center gap-2 font-mono text-xs">
          <button
            onClick={handleCopy}
            className="px-3 py-1.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 flex items-center gap-1.5 transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied Markdown' : 'Copy Text'}</span>
          </button>
          <button
            onClick={handleDownload}
            className="px-3.5 py-1.5 rounded bg-indigo-600 hover:bg-indigo-500 text-white flex items-center gap-1.5 transition-colors font-medium"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download Report (.md)</span>
          </button>
        </div>
      </div>

      {/* Markdown Preview Canvas */}
      <div className="glass-panel p-6 rounded-lg space-y-4">
        {loading ? (
          <div className="p-12 text-center text-slate-400 font-mono text-xs">
            Synthesizing executive briefing report...
          </div>
        ) : (
          <div className="prose prose-invert max-w-none font-sans text-xs leading-relaxed space-y-4">
            <div className="p-4 rounded bg-slate-950 border border-slate-800 font-mono text-xs whitespace-pre-wrap leading-relaxed text-slate-200">
              {reportData?.report_md}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
